# This is a basic workflow to help you get started with Actions

name: Codeforces Upload Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
    - master
    - feature/*
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
#  extracted:
#    runs-on: ubuntu-latest
#    
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-python@v2.2.2 
#
#      - name: Install Python Requirements
#        run: if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi 
#      
#      - name: Extract
#        run: python run.py extract
#      
#      - name: Check git status
#        run: |
#          echo 'Diff:'
#          git diff
#         python run.py is_extracted
      
  # This workflow contains a single job called "build"
  is-extracted:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2.1.3
    - uses: actions/setup-python@v2.2.2
    
    
    - name: Install Python Requirements
      run: if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
    
    - name: Check if extracted
      run: | 
        python run.py extract
        git status
        git diff
        git add templates/
        git commit -m"extract"
        python run.py check-extracted
        


  codeforces-uploads:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2.1.3
      - uses: actions/setup-python@v2.2.2
      
      - name: Install Python Requirements
        run: if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi


      - name: Install cf-tool
        run: |
          wget https://github.com/Komosa/cf_binaries/raw/master/cf_linux_amd64
          mv cf_linux_amd64 ./cf
          chmod +x ./cf
          
      - name: Codeforces login
        run: |
          mkdir ~/.config/cf
          touch ~/.config/cf/config
          echo 'cpp=61' >> ~/.config/cf/config
          echo ${{ secrets.ONE }} >> ~/.config/cf/config
          echo ${{ secrets.TWO }} >> ~/.config/cf/config
          echo ${{ secrets.THREE }} >> ~/.config/cf/config
          cat ~/.config/cf/config
          ./cf login
      
      

      - name: Submit to Codeforces
        run: python run.py test
